#' Perform Single-Cell Quality Control for 10x Genomics Data
#'
#' This function performs a series of quality control (QC) steps on single-cell RNA sequencing data 
#' generated by 10x Genomics. It includes reading the data, detecting and removing empty droplets, 
#' calculating per-cell QC metrics, applying dataset-sensitive and custom filters, and generating 
#' filtered datasets.
#'
#' @param x10_file_path Character. Path to the 10x Genomics data directory.
#' @param empty_droplets_fdr_threshold Numeric. False discovery rate (FDR) threshold for identifying 
#' empty droplets. Default is 0.01.
#' @param empty_lower_droplets Logical. Whether to use a lower threshold for detecting empty droplets. 
#' Default is TRUE.
#' @param replace_unfiltered Logical. Whether to replace existing unfiltered data columns in the 
#' SingleCellExperiment object. Default is TRUE.
#' @param save_dataset_sensitive_filtering Logical. Whether to save the dataset-sensitive filtered 
#' dataset instead of the custom filtered dataset. Default is TRUE.
#' @param BPPARAM A BiocParallel parameter object specifying parallelization settings. Default is 
#' `BiocParallel::SerialParam()`.
#'
#' @return A list of `targets` objects representing the QC pipeline steps, including:
#' \itemize{
#'   \item `path`: The input file path.
#'   \item `sce_raw`: The raw SingleCellExperiment object.
#'   \item `empty_droplets`: Results of empty droplet detection.
#'   \item `sce_no_empty_drop`: SingleCellExperiment object after removing empty droplets.
#'   \item `per_cell_qc_metrics`: Per-cell QC metrics.
#'   \item `sce_unfiltered`: SingleCellExperiment object with unfiltered data and QC metrics.
#'   \item `sce_sensitive_filter`: Dataset-sensitive filtered SingleCellExperiment object.
#'   \item `sce_custom_filter`: Custom filtered SingleCellExperiment object.
#'   \item `sce_filtered`: Final filtered SingleCellExperiment object based on the selected filtering strategy.
#' }
#'
#' @details
#' The function performs the following steps:
#' \enumerate{
#'   \item Reads the 10x Genomics data and creates a raw SingleCellExperiment object.
#'   \item Detects empty droplets using the `DropletUtils::emptyDrops` function.
#'   \item Removes empty droplets based on the specified FDR threshold.
#'   \item Calculates per-cell QC metrics, including mitochondrial and ribosomal gene percentages.
#'   \item Applies dataset-sensitive and custom filters to identify low-quality cells.
#'   \item Generates filtered datasets based on the selected filtering strategy.
#' }
#'
#' @examples
#' \dontrun{
#' tar_sc_single_qc(
#'   x10_file_path = "/path/to/10x/data",
#'   empty_droplets_fdr_threshold = 0.01,
#'   empty_lower_droplets = TRUE,
#'   replace_unfiltered = TRUE,
#'   save_dataset_sensitive_filtering = TRUE,
#'   BPPARAM = BiocParallel::SerialParam()
#' )
#' }
#'
#' @importFrom DropletUtils emptyDrops
#' @importFrom scater perCellQCMetrics isOutlier
#' @importFrom purrr map reduce
#' @importFrom tidyr replace_na
#' @importFrom stringr str_which regex
#' @importFrom BiocParallel SerialParam
#' @importFrom SingleCellExperiment colData rowData counts
#' @export

tar_sc_single_qc <- function(
  name,
  x10_file_path,
  empty_droplets_fdr_threshold = 0.01,
  mad_threshold = 3,
  min_umi_cf = 1000,
  max_umi_cf = 50000,
  min_feature = 1000,
  max_mito_ratio = 0.2,
  replace_unfiltered = TRUE,
  save_dataset_sensitive_filtering = TRUE,
  min_umi = 1,
  min_ratio_cells = 0.01,
  BPPARAM = BiocParallel::SerialParam()
) {

  targets::tar_assert_path(x10_file_path, 'Input path for 10x data was not found.')

  list(
    tar_target_raw("path", x10_file_path, format = "file"),
    tar_target_raw(
      name = "sce_raw", 
      command = quote(scTargets::tar_sc_single_qc_step_read_10x_counts(path))
    ),
    tar_target_raw(
      name = "empty_droplets", 
      command = substitute(
        scTargets::empty_droplets(sce_raw, BPPARAM),
        env = list(BPPARAM = BPPARAM)
      )
    ),
    tar_target_raw(
      name = "sce_valid_cells", 
      command = substitute(
        scTargets::remove_empty_drop(sce_raw, empty_droplets, empty_droplets_fdr_threshold),
        env = list(empty_droplets_fdr_threshold = empty_droplets_fdr_threshold)
      )
    ),
    tar_target_raw(
      name = "sce_unfiltered", 
      command = substitute(
        scTargets::create_unfiltered_sce(
          sce_no_empty_drop,
          replace_unfiltered,
          mad_threshold,
          min_umi_cf,
          max_umi_cf,
          min_feature,
          max_mito_ratio,
          replace_unfiltered,
          BPPARAM = BiocParallel::SerialParam()
        ),
        env = list(
          replace_unfiltered = replace_unfiltered, 
          mad_threshold = mad_threshold,
          min_umi_cf = min_umi_cf,
          max_umi_cf = max_umi_cf,
          min_feature = min_feature,
          max_mito_ratio = max_mito_ratio,
          replace_unfiltered = replace_unfiltered,
          BPPARAM = BPPARAM
        )
      )
    ),
    tar_target_raw(
      name = "sce_filtered", 
      command = substitute(
        scTargets::apply_filter(
          sce_unfiltered,
          save_dataset_sensitive_filtering,
          min_umi,
          min_ratio_cells
        ),
        env = list(
          save_dataset_sensitive_filtering = save_dataset_sensitive_filtering,
          min_umi = min_umi,
          min_ratio_cells = min_ratio_cells
        )
      )
    )
  )
}


